XENON1T/cax

cax/main.py, cax/task.py, cax/tasks/checksum.py, cax/tasks/clear.py, cax/tasks/data_mover.py, cax/tasks/process.py
This pull request fixes many issues we've been having with data transfers.
1.  There was a bug from introducing automatic data processing.  We would only copy either raw or processed data, but not both.
2.  Data transfers will timeout.  After 1 day, we get warning.  After 2, it deletes failed copy if partially transferred.  It also updates the rundb so it should retransfer.  It only deletes if there are enough copies around.
3. Similarly for checksum failures.  If enough good copies and local copy has checksum failure, it will delete local copy and retransfer.
4. Checksums for processed data (this wasn't implemented).
5. Compression in transfers (2-3x increase in speed)
6. Fix timeout with MongoDB where MongoDB times out if not contact in while, which happens if we are SCPing large …
=> Fix many transfer issues and recover from common problems

cax/config.py, cax/tasks/data_mover.py
Each time we reprocess data with a new pax version the basic directory which is created at the PDC Stockholm (/cfs/klemming/projects/xenon/xenon1t/processed/pax_vX.x.x/) has the wrong permissions. This fix adjust the permissions for Stockholm.
=> Set basic_dir permissions correct for processed data at init

cax/config.py
Just a minor adjustment: I changed recently the installation directory at the PDC of the Anaconda installation back to the common xenon1t software folder. I changed the path in cax too.
This change is only important for reprocessing data at Stockholm.
=> Change path to Anaconda Installation at PDC

cax/tasks/process.py
In pax 6 the queues are handled by seperate plugins rather than the core. Hence the option for maximum queue size has to go to the Queues section.
=> Fix for pax 6: queue size option relocation

cax/tasks/process.py
Pax by default groups events in blocks of 10 when it puts them on internal/remote queues. On midway we process XENON1T events at a few events/sec (for which 4 CPUs have to work together), so this block grouping doesn't help performance. Moreover, it increases the memory requirement of pax and increases the possibility of timeouts (when a few very large events choke the workers).
=> Reduce pax queue block size in batch processing

cax/tasks/clear.py
It prevent the purge process for Rn220 and Kr83m dataset in Midway-login1, while they are purged in the other hosts.
=> New purge rules for Rn220/Kr83m

cax/tasks/process_hax.py
This adds other common treemakers to process_hax:
* TotalProperties: https://github.com/XENON1T/hax/pull/40, which calculates amongst others the total area in all peaks;
* DoubleScatter, Ted's treemaker used especially for Kr83m analysis: https://github.com/XENON1T/hax/pull/36;
* LargestPeakProperties: an older treemaker that may still be useful for studying lone-S2 and lone-S1 events.
=> Add other treemakers to process_hax

cax/tasks/clear.py
This makes cax wait 24 hours to purge errored data since @coderdj didn't like that it was clearing data when DAQ crashed.
=> Don't purge errored data promptly

cax/cax.json, cax/tasks/checksum.py, cax/tasks/clear.py, cax/tasks/data_mover.py
Implement ```rsync``` mode for data transfers for capability to resume stalled or failed transfers, instead of purging and starting from the beginning. ```rsync``` should also provide better throughput than ```scp```.
```purge``` function needed to be changed to prevent the deletion of raw data in these cases, but be warned that scp will now create undesired nested directories without this prior cleanup.
=> Implement rsync

cax/tasks/corrections.py
This gives the gain model access to the start time of the run.
=> Allow gains to use the time of the run

cax/main.py, cax/tasks/corrections.py, cax/tasks/process.py, cax/tasks/process_hax.py
We have taken runs at several different drift fields, and therefore different drift velocities. Pax needs to know the drift velocity to compute the z-position of an interaction (and thus the S1(x,y,z) correction). Currently the drift velocity is simply hardcoded in the pax configuration.
This adds a hax task to compute the drift velocity for each run based on the cathode voltage. Almost all runs should fall exactly on one of the datapoints in [my diffusion and drift note](https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:aalbers:drift_and_diffusion#results). For the few runs which might not, we compute the drift velocity on a power-law fit:
The error bars on the measurements are not very large, see the note linked above.
Naturally we should not rely on this or any fit for …
=> Compute drift velocity for each run

cax/tasks/corrections.py
#75 accidentally contained two drift velocity functions after another. Unfortunately the incorrect one was last, and all our runs are now being processed with the wrong drift velocity. 
This removes the spurious extra function. The remaining one is correct: 
(42.2266 *12 - 268.6557)**0.067018 = 1.4429, which is within the error of the value (1.440) determined  in https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:aalbers:drift_and_diffusion#results
Thanks to @lgrandi for spotting the z vs dt offset.
=> Remove "bonus" drift velocity function

cax/tasks/process_hax.py
This adds the Extended minitree, which contains variables needed for several sciencerun0 cuts, to the list of auto-computed minitrees.
=> Add Extended minitree to auto-computed minitrees

cax/config.py, cax/main.py, cax/tasks/clear.py
To use the new task you must add in the *.json file a new entry to specify the pax version that you want to purge:
` [`
`   {`
`     "name": "midway-login1",`
`     "method": "scp",`
`     "hostname": "midway-login1.rcc.uchicago.edu",`
`     "dir_raw": "/project/lgrandi/xenon1t/raw",`
`     "dir_processed": "/project/lgrandi/xenon1t/processed",`
`     "upload_options": [],`
`     "username": "tunnell",`
`     "download_options": [],`
`     "task_list": ["PurgeProcessed"],`
`     "purge" : 2,`
`     "pax_version_purge" : "v6.1.0"`
`   }`
` ]`
`
=> Purge processed root files implemented on the last cax version

cax/main.py, cax/tasks/checksum.py, cax/tasks/clear.py, cax/tasks/data_mover.py
* Move purge tasks to end (after processing)
* Count 'rucio-catalog' as a good copy (even though it has different checksum)
* Disable Midway purge exceptions (all will be purged now)
* Create function to check purge rules
* Use in CopyPull task to ignore these files
=> Purge updates (for Midway)

.gitignore, cax/config.py, cax/main.py, cax/task.py, cax/tasks/corrections.py, examples/Drift velocity to runs db.ipynb, setup.cfg, setup.py, tests/common.py, tests/test_cax.py, tests/test_corrections.py
This adds:
- Version tracking for corrections (#81) 
- Tests for cax using a fake runs db
- Make the drift velocity 'correction' play by the rules (sympy function in runs db), and include Julien's measurements at lower fields.
Correction versioning
--------------------------
As several of you know, our corrections are controlled by documents in special collections in the runs db (e.g. 'purity' for electron lifetime). These contain a sympy function which computes the correction value, as well as a 'creation_time' key, which cax uses to figure out which correction is the most recent (and should therefore be used).
With this pull request:
* Corrections can be identified by an explicit `version` string in the correction doc. If that's not there, we just use a timestamp string from the …
=> Correction versioning, tests with fake runs db, drift velocity

cax/tasks/corrections.py
Apparently sympy outputs its own float (probably for high precision) that mongo does not want to eat
=> Convert to standard float in AddDriftVelocity

cax/tasks/corrections.py
Defining the variable first before running evalf worked in my notebook. The way it was before (not defining variable) did not work. So I added one line before eval line:
<code>
t = sympy.symbols('t', integer=True)
</code>
=> fix for purity correction

cax/tasks/corrections.py
pax will interpret the '|' as a '.' when doing the config override, so the setting will be taken correctly.
=> Add '|' character to avoid autonesting by mongo

cax/qsub.py, cax/tasks/process.py, cax/tasks/process_hax.py
Remove Midway-only constraint.
This only allows ```cax``` to run locally on e.g. ```xecluster06```.  @malfonsi working on implementing ULITE for ```massive-cax```
=> Allow processing anywhere

cax/tasks/data_mover.py
Previously implemented exception for pulling expired raw files was preventing the download of newly processed files.  This just applies the requirement to raw files only, as was originally intended.
=> Download processed files even if past purge threshold

cax/tasks/process_hax.py
Fixes issue reported by @ftoschi and @coderdj about wrong pax file used in hax minitree generation when older pax version was expected.
Main change is including ```pax_version_policy``` in ```hax.init```.
=> Fix pax versioning in hax task

cax/config.py
to prevent ROOT library recompilation (fixes #118), while keeping logs in their respective dirs.
This does not actually solve the underlying issue described in #118, but should be fine as long as running from the same directory is OK (which should be find since I kept the log writing into separate directories).
Note: ```rm -f ${{JOB_WORKING_DIR}}/pax_event_class*``` is temporarily kept to clean up directories after jobs were prematurely killed.
=> Make all cax jobs run in same directory

cax/tasks/corrections.py
Loading the e-lifetime function was taking a significant amount of time per cax job even though it is not used when correction version hasn't changed.  This PR just moves the loading of the function to after the version check.
=> Only load huge sympy function if version changed

cax/main.py, cax/tasks/filesystem.py
Fixes #86:
I added a new task called `AddSize` to evaluate and check the size of raw data and their completeness.
I tested the script only from midway, but I think it should work on xe1t-datamanager as default before to start the copy with Rucio. 
I didn't set a particular host where it have to work, because in general should be able to verify the raw in each site and then evaluate the size (this is a kind of double check in case of multiple copies of raw data)
To use it is enough add in the task list `"AddSize"`
=> Added new class in cax/tasks/filesystem.py to add the raw size in byte

cax/tasks/filesystem.py
Together with @XeBoris  yesterday we found a stupid bug that provide an error when the files are not yet transferred. Basically I initialized a variable with the total number of triggered event before to verify that the file is complete reading the run_doc["trigger"]["events_build"].
Now Fixed and tested on datamanager
=> fixed a bug for the raw data not yet transferred

cax/tasks/clear.py
Fixes #40 
Though should try to fix ```creation_time``` format in RunsDB retroactively.
Currently manually installed in ```pax_v6.8.0``` environment as a temporary workaround.
=> Fix for inconsistent creation_time formats in RunsDB (#40)

cax/tasks/filesystem.py
I had to make a check for the trigger field `events_build` because still provide an error.
I found a problem on datamanager there are several very old data (161130_1114 for example) where my user don't have permission to read the data. 
@XeBoris can you check the permission on the rucio/tsm side??
Anyway the code seems to work fine in all the other cases.
=> tigger events_build error still present. Fixed with a check

cax/tasks/filesystem.py
inconsistent use of tab error found on midway, not on datamanager
=> removed a stupid tab at line 194

cax/main.py
Re-enable "iterative" mode, which only loops over most recent runs after one full iteration, to reduce the total number of jobs submitted over time.
During massive reprocessings, then ```massive-cax``` should be restarted manually to catch any stragglers.
Better, but longer-term solution of Implementing a check prior to submitting any job still to be considered.
=> Reinstate iterative mode

cax/tasks/clear.py
Should fix this error that appeared while running cax daemon in local mode:
```
File "/project/lgrandi/anaconda3/envs/pax_v6.8.0/lib/python3.4/site-packages/cax-5.2.1-py3.4.egg/cax/tasks/clear.py", line 99, in each_location
data_doc['type'], data_doc['pax_version']))
KeyError: 'pax_version'
```
=> Only print pax version for processed data

cax/tasks/process_hax.py
Switch to new ```CorrectedDoubleS1Scatter``` treemaker by @ctherreau after merging https://github.com/XENON1T/hax/pull/163
=> Swap to new CorrectedDoubleS1Scatter treemaker

cax/tasks/clear.py
without requiring 2 copies like raw
=> Purge bad checksummed processed data

cax/main.py, cax/tasks/corrections.py
I think this is all that's needed, right? Removed the function from corrections.py and took the task out of the task list.
For posterity we're removing this correction because it is now done in hax and the outdated format expected by cax was causing problems in processing when it defaulted to zero.
=> Remove electron lifetime from corrections and task list

cax/config.py, cax/qsub.py
Automatically get username when checking queue count for pausing ```massive-cax``` (wasn't working after switching users since username was hardcoded).
=> Use correct username when checking queue count

cax/tasks/process_hax.py
If a minitree is corrupt, hax just crashes when trying to load it and doesn't regenerate. This PR allows cax to detect that crash, delete the corrupt minitree and retry.
Note: this will retry on any exception, not just corrupt file error.
=> Retry corrupt minitree generation

cax/main.py
This disables cax tasks that added run doc overrides for corrections that have moved to hax. These are now so far out of date the correction map files they reference no longer exist, breaking various things (shifter notebooks, waveform inspection code, etc). 
After merging this, we'd still have to
* Update the cax(es) that runs the correction tasks (I don't know where); unless this happens automatically
* Scrub the references to the outdated correction maps from the run docs (I could do this).
The alternative to this is to update the corrections db with all the new corrections in hax.ini. I doubt we want to to do this and maintain two separate systems.
=> Disable corrections that moved to hax
