XENON1T/cax

- AUTHORS.rst
- README.rst
Just a cleanup so I can give a copy of this information to Nikhef IT guys.
> Various documentation changes

- cax/config.py
- cax/main.py
- cax/task.py
- cax/tasks/corrections.py
- setup.py
This pull request uses the HTTP interface to the slow control system instead of the MongoDB Historian mirror to obtain voltages.  These voltages are then used to determine gain.
> New gain derivation method

- cax/tasks/checksum.py
This checks that the checksum for existing data agrees.  If it doesn't, then it adds a field:
checksumproblem
Eventually, we can automate the response, but for now I just want an extra field.
> Confirm checksum of existing data

- cax/cax.json
- cax/config.py
- cax/main.py
- cax/tasks/checksum.py
- cax/tasks/clear.py
Implement purge logic, where if data is old and there are enough copies, delete it.  The copies are hard coded to 2.  The number of days is configurable and currently 60.  I did the following tests:
- Run 216: old with many copies, it purged from Midway.
- Run 2910: shouldn't purge since new, didn't purge.
- Run 319: Shouldn't delete since not enough copies, and didn't delete
(Also run 2819 and 2849 might be lost)
If we can review quick, can test on datamanager too.  Just tested on Midway.  I'd like to purge soon for data taking reasons and because I want to watch it.
> Purge logic

- cax/tasks/corrections.py
> Change to DAQ gateway wrapper for slow control

- cax/tasks/process.py
In pax 6, the API for calling multiprocessing has changed: the `cpus` option has been removed in favor of the `parallel.multiprocess_locally` function. This changes process.py in cax to call this new function.
Note that, as written, this is incompatible with pax <6.0.0; after you merge this cax can no longer process data with these old versions of pax.
> Update process.py for pax 6.0.0

- cax/cax.json
- cax/config.py
- cax/main.py
- cax/qsub.py
- cax/tasks/process_hax.py
Patrick and I wrote a piece of script to produce hax minitrees. This script does not affect the run database. We'd like to use it to produce common minitrees for all pax versions and those minitrees can be accessed by anyone for analysis.
> minitree production

- cax/config.py
- cax/main.py
- cax/tasks/data_mover.py
- cax/tasks/filesystem.py
Adjusted ownership/permissions in SetPermissons - class for:
Tegner:
* user: bobau | group: xenon-users
* permissions: 750
* 'setfacl /some/path/with/permissions/ (processed files / raw data)
Midway:
* user: tunnell | group: xenon-admins
* permissions 755
Change ownership and permission during eat iteration of cax.
> Setpermission

- cax/tasks/process.py
Fixes https://github.com/XENON1T/pax/issues/463
> Fixes for MV and long event processing

- cax/tasks/clear.py
I suspect that ```massive-cax``` running on Midway is delayed for too long when running in iterative mode, such that when it reaches the old runs processed by OSG it's beyond the 24-hour mark and purges it. 
For example, for run 2119, log on Stash ```/xenon/ershockley/reprocessing/v6.1.1/160813_1414/POST_LOG``` shows:
```
Fri Dec  9 03:54:40 CST 2016
root        : INFO     upload: /xenon/ershockley/processed/pax_v6.1.1/160813_1414.root to /project/lgrandi/xenon1t/processed/pax_v6.1.1/160813_1414.root
CopyPush    : INFO     scp upload dataset 160813_1414.root took 80 seconds
```
while on Midway ```/project/lgrandi/xenon1t/cax/2119_v6.1.0/cax.log``` shows:
```
cax_v4.10.4 - 2016-12-10 10:02:32,882 [INFO] Executing AddChecksum.
cax_v4.10.4 - 2016-12-10 10:03:59,045 [INFO] Checksum fail 2119 …
```
> Potential solution to missing OSG processed files

- cax/main.py
See #27. Maybe not the most important issue :-)
> --version argument

- cax/tasks/process_hax.py
> Make S2 tail cut minitree by default

- cax/tasks/corrections.py
remove slow voltage query since not needed
> remove voltage query from get gains

- cax/main.py
Should be clear why the new corrections could not work without this step. Whoops.
> Added new corrections tasks to main.py task list

- cax/main.py
accidentally removed on [10/04/2017](https://github.com/XENON1T/cax/commit/1c1f314b4ae2b61874e84b199291c49084b4fc49#commitcomment-22353085)
> Restore purge tasks

- cax/tasks/process_hax.py
for https://github.com/XENON1T/hax/pull/109
> Add Corrections treemaker

- cax/tasks/process_hax.py
> hax load single dataset

- cax/tasks/process_hax.py
According to https://github.com/XENON1T/hax/pull/127
> Remove TailCut minitree

- cax/tasks/process_hax.py
Just to add two other treemaker in tast list.
> add ac analysis treemaker in the list

- cax/tasks/filesystem.py
I found in a stupid print for debug info some old variable names anymore defined
> Cax file size

- cax/tasks/filesystem.py
I moved the position of nfiles because create the permission error.
> moved the file number counter inside the check of raw_size_byte

- cax/main.py
since new data and online processing comes in on the order of hours
> Re-enable pause at end of run loop, extend to 1 hr

- cax/tasks/process_hax.py
https://github.com/XENON1T/hax/pull/164
> Add new FlashIdentification treemaker

- cax/config.py
in case of switching cax daemon user
> Make log dirs xenon1t-admin group

- cax/main.py
Submission pausing wasn't working before, this should fix it.
> Make submission pause actually work

- cax/tasks/process_hax.py
Following https://github.com/XENON1T/hax/pull/203 and https://github.com/XENON1T/hax/pull/207
> Add SE (IsolatedPeaks) treemaker

- cax/tasks/process_hax.py
Following https://github.com/XENON1T/hax/pull/214
> Add SingleElectrons treemaker

- cax/cax_ruciax.json
- cax/cax_ruciax_download.json
- cax/cax_ruciax_verifyruns.json
- cax/cax_tsm_download.json
- cax/cax_tsm_upload.json
- cax/tasks/filesystem.py
Switch Midway responsible user to ```pdeperio```. 
@XeBoris: Please check all your ```.json```s, not sure if you need special setup in my account for rucio?
> Switch user to pdeperio
